version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - gradle build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - build/libs/academai-spring-boot-0.0.1-SNAPSHOT.jar